### ISSUE TITLE
Backup name format does not match the Bigtable Admin API

### ISSUE THREAD

**Issue by AmitMatsil** [googleapis/python-bigtable#969]
The regular expression used in [backup.py](https://github.com/googleapis/python-bigtable/blob/v2.23.1/google/cloud/bigtable/backup.py#L31) does not match the format specified in the [Bigtable Admin API](https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.clusters.backups/create).

#### Environment details

  - OS type and version: Mac OC 13.6.6
  - Python version:  3.11.8
  - pip version: 22.3.1 
  - `google-cloud-bigtable` version: 2.22.0

#### Steps to reproduce

  1. Create a Bigtable table instance
  2. Call the list_backup method

#### Code example

```python
from google.cloud import bigtable

client = bigtable.Client(admin=True, project='XXXX')
instance = client.instance('XXXX')
instance.table('_locks_').list_backups()
```

#### Stack trace
```
Traceback (most recent call last):
  File "XXX/bigtable_regex_error.py", line 5, in <module>
    instance.table('_locks_').list_backups()
  File "XXX/venv/lib/python3.11/site-packages/google/cloud/bigtable/table.py", line 1000, in list_backups
    result.append(Backup.from_pb(backup_pb, self._instance))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX/venv/lib/python3.11/site-packages/google/cloud/bigtable/backup.py", line 253, in from_pb
    raise ValueError(
ValueError: ('Backup protobuf name was not in the expected format.', 'projects/XXXX/instances/XXXX/clusters/XXXX/backups/_locks_-backup-20240527-0700')
```

**Comment by AmitMatsil** [comment]
PR created https://github.com/googleapis/python-bigtable/pull/970.
